
server:
  port: 8002

spring:
  application:
    name: redis-cache-example

  datasource:
    url: jdbc:mysql://localhost:3306/my_schema?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Endless1309
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
     hibernate:
      format-sql: true
    hibernate:
        ddl-auto: 'create-drop'

  cache:
    type: redis
    redis:
      time-to-live: 10000
      key-prefix: radha
  redis:
    host: localhost
    port: 6379